[theme]
name = DoiZ
mode = dark

[colors]
background = #1A1D33
surface = #2B2F52
surface_alt = #383D6A
foreground = #D6DAED
subtext = #A5ABCD
muted = #6E76A0
accent = #3F458C
accent_alt = #6D72A8
accent_dark = #262954
blue = #6A85CC
cyan = #617BCA
green = #81AA99
red = #B2729E
yellow = #AA978B
dominant = #1B1C29

[dynamic]
enabled = true
source = wallpaper
extractor = colorthief
update_on_wallpaper_change = true

[targets]
waybar = true
quickshell = true
btop = true
kitty = true
rofi = true
gtk = true
cava = true

