hl.config({
    autogenerated = false,
})

require("config.env")
require("config.programs")
require("config.monitors")
require("config.workspaces")
require("config.input")
require("config.mouse")
require("config.visuals")
require("config.animations")
require("config.decoration")
require("config.layout")
require("config.keybinds")
require("config.windowrules")
require("config.layerrules")
require("config.misc")
require("config.debug")

local custom = require("local.custom")

if custom and custom.apply then
    custom.apply()
end

require("config.autostart")