font_family JetBrainsMono Nerd Font
font_size 12.0

background #0B0D17
foreground #CDD6F4

background_opacity 0.20
dynamic_background_opacity yes

cursor #CBA6F7
cursor_text_color #0B0D17

selection_background #40305F
selection_foreground #CDD6F4

window_padding_width 14
window_margin_width 8

hide_window_decorations yes
remember_window_size no

enable_audio_bell no
visual_bell_duration 0

cursor_shape block
cursor_blink_interval 0.5

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1

scrollback_lines 10000

sync_to_monitor yes
repaint_delay 10
input_delay 3
confirm_os_window_close 0
allow_remote_control yes

color0 #1E1E2E
color1 #F38BA8
color2 #A6E3A1
color3 #F9E2AF
color4 #89B4FA
color5 #CBA6F7
color6 #7AA2F7
color7 #CDD6F4
color8 #444B6A
color9 #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #CBA6F7
color14 #7AA2F7
color15 #FFFFFF

include theme.conf
