foreground #CDD6F4
background #0B0D17

cursor #CBA6F7
cursor_text_color #0B0D17

selection_foreground #CDD6F4
selection_background #40305F

color0 #1E1E2E
color1 #F38BA8
color2 #A6E3A1
color3 #F9E2AF
color4 #89B4FA
color5 #CBA6F7
color6 #7AA2F7
color7 #CDD6F4

color8 #444B6A
color9 #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #CBA6F7
color14 #7AA2F7
color15 #FFFFFF