theme[main_bg]="#1A1D33"
theme[main_fg]="#D6DAED"

theme[title]="#D6DAED"
theme[hi_fg]="#3F458C"

theme[selected_bg]="#2B2F52"
theme[selected_fg]="#3F458C"

theme[inactive_fg]="#6E76A0"
theme[graph_text]="#A5ABCD"
theme[meter_bg]="#383D6A"

theme[proc_misc]="#6A85CC"
theme[cpu_box]="#3F458C"
theme[mem_box]="#81AA99"
theme[net_box]="#6A85CC"
theme[proc_box]="#617BCA"
theme[div_line]="#383D6A"

theme[temp_start]="#81AA99"
theme[temp_mid]="#AA978B"
theme[temp_end]="#B2729E"

theme[cpu_start]="#6A85CC"
theme[cpu_mid]="#617BCA"
theme[cpu_end]="#3F458C"

theme[free_start]="#81AA99"
theme[free_mid]="#6A85CC"
theme[free_end]="#3F458C"

theme[cached_start]="#6A85CC"
theme[cached_mid]="#617BCA"
theme[cached_end]="#3F458C"

theme[available_start]="#AA978B"
theme[available_mid]="#B2729E"
theme[available_end]="#B2729E"

theme[used_start]="#81AA99"
theme[used_mid]="#617BCA"
theme[used_end]="#6A85CC"

theme[download_start]="#6A85CC"
theme[download_mid]="#617BCA"
theme[download_end]="#3F458C"

theme[upload_start]="#3F458C"
theme[upload_mid]="#B2729E"
theme[upload_end]="#B2729E"

theme[process_start]="#6A85CC"
theme[process_mid]="#617BCA"
theme[process_end]="#3F458C"

theme[read_start]="#6A85CC"
theme[read_mid]="#617BCA"
theme[read_end]="#81AA99"

theme[write_start]="#3F458C"
theme[write_mid]="#AA978B"
theme[write_end]="#B2729E"

theme[proc_pause_bg]="#2B2F52"
theme[proc_follow_bg]="#383D6A"
theme[proc_banner_bg]="#2B2F52"
theme[proc_banner_fg]="#D6DAED"

theme[followed_bg]="#2B2F52"
theme[followed_fg]="#3F458C"
